### PR TITLE
Remove/Edit k8s conformance jobs for docker deprecation

### PR DESCRIPTION
**Pull request by Rajalakshmi-Girish**
Part of task https://github.ibm.com/powercloud/container-dev/issues/1544

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by mkumatag** [comment]
/hold

I see wip tag, feel free to unhold whenever you are okay @Rajalakshmi-Girish

**Comment by Rajalakshmi-Girish** [comment]
> /hold
> 
> I see wip tag, feel free to unhold whenever you are okay @Rajalakshmi-Girish

Switching `postsubmit-master-golang-kubernetes-conformance-test-ppc64le ` job from docker to containerd is causing the `SystemOOM` very quick and thereby the ansible-playbook is failing as node is becoming unreachable.
Shall we go ahead with this change waiting for master golang fix?

**Comment by Rajalakshmi-Girish** [comment]
https://prow.ppc64le-cloud.org/job-history/s3/prow-logs/logs/test-postsubmit-master-golang-kubernetes-conformance-test-ppc64le is where you can find job runs with containerd.

**Comment by mkumatag** [comment]
> https://prow.ppc64le-cloud.org/job-history/s3/prow-logs/logs/test-postsubmit-master-golang-kubernetes-conformance-test-ppc64le is where you can find job runs with containerd.

anyways it is failing, I don't see any other way to fix this. Lets merge.

**Pull request merged**
