### PR TITLE
bump terraform version

### PR DESCRIPTION
**Pull request by RagniGarg97**
Terraform version 13 will need terraform-provider-ibm and terraform-provider-null in the .terraform folder while running the jobs.
```
- plugins
- - selections.json
- - registry.terraform.io
- - - hashicorp
- - - - ibm
- - - - - 1.13.1
- - - - - - linux_ppc64le
- - - - - - - terraform-provider-ibm
- - - - null
- - - - - 2.1.0
- - - - - - linux_ppc64le
- - - - - - - terraform-provider-null

```

so instead for installing the plugins in each job, it is taken care of in all-in-one image itself.

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/174#" title="Author self-approved">RagniGarg97</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mkumatag** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @mkumatag` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by Rajalakshmi-Girish** [comment]
@RagniGarg97 I get the below error while I tried to run the conformance job with the all-in-one image `quay.io/ragnigarg97/all-in-one:ppc` that you mentioned to have built with changes in this PR:

```
Error: Failed to install provider

Error while installing hashicorp/ibm: provider registry registry.terraform.io
does not have a provider named registry.terraform.io/hashicorp/ibm

Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/ibm versions matching ">= 1.9.0"...
- Finding latest version of hashicorp/null...

Error: Failed to install provider

Error while installing hashicorp/null v3.1.0: provider
registry.terraform.io/hashicorp/null 3.1.0 is not available for linux_ppc64le


Error: Failed to install provider

Error while installing hashicorp/ibm: provider registry registry.terraform.io
does not have a provider named registry.terraform.io/hashicorp/ibm

terraform.Output:
terraform.Output error: failed to initialize Terraform
I0415 17:31:58.850402    3179 deployer.go:140] Terraform Apply failed. Look into it and delete the resources
I0415 17:31:58.850459    3179 deployer.go:141] terraform.Apply error: failed to initialize Terraform
{"component":"unset","error":"wrapped process failed: exit status 1","file":"/go/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-04-15T17:31:58Z"}
```

**Comment by Rajalakshmi-Girish** [comment]
I don't see the `.terraform` folder created in the pod with image created with this Dockerfile.
```
root@detoxing1:~/rajalakshmi# cat sample.yaml
apiVersion: v1
kind: Pod
metadata:
 name: ragniall-in-one
spec:
 containers:
   - image: quay.io/ragnigarg97/all-in-one:ppc
     name: ragniall-in-one
     command: [ "sleep" ]
     args: [ "infinity" ]
root@detoxing1:~/rajalakshmi#
kubectl apply -f sample.yaml
pod/ragniall-in-one created
root@detoxing1:~/rajalakshmi# kubectl exec -it ragniall-in-one /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@ragniall-in-one:/workspace# cd ~
root@ragniall-in-one:~# ls -a
.  ..  .bashrc  .bluemix  .cache  .config  .profile  .wget-hsts
root@ragniall-in-one:~#
```


1. TF_PLUGIN_PATH has a slash after the directory name hashicorp, also there is a slash after $TF_PLUGIN_PATH while you create using RUN mkdir.
```
ARG TF_PLUGIN_PATH=$HOME/.terraform/plugins/registry.terraform.io/hashicorp/
RUN  mkdir -p ${TF_PLUGIN_PATH}/ibm/${TERRAFORM_PROVIDER_IBM_VERSION}/linux_`go env GOARCH`
```
2. But the above extra slash might not be the reason for not having .terraform created. @RagniGarg97 Can you please check and confirm.

**Comment by Rajalakshmi-Girish** [comment]
I could figure out the reason for this!
You missed setting the ENV variable for newly added TF variables. Mere defining ARG wouldn't assign the values.
Please set the ENV in the below fashion:
```
ARG TF_VERSION
ENV TF_VERSION ${TF_VERSION:-v0.13.6}
```
As the values of TF_PLUGIN_PATH, TERRAFORM_PROVIDER_NULL_VERSION, TERRAFORM_PROVIDER_IBM_VERSION are not set, the mkdir is only creating "/ibm/linux_ppc64le/"
```
root@ragniall-in-one:/workspace# find / -name "terraform-provider-ibm"
/workspace/terraform-provider-ibm
/ibm/linux_ppc64le/terraform-provider-ibm
root@ragniall-in-one:/workspace# command terminated with exit code 137
root@detoxing1:~/rajalakshmi#
```

**Comment by mkumatag** [comment]
closing in favor of #179

**Pull request closed without merging**
