### PR TITLE
Update all-in-one image 0.5

### PR DESCRIPTION
**Pull request by mkumatag**

### CODE REVIEW

**Review by Rajalakshmi-Girish — CHANGES_REQUESTED** [review]
I did a test run of k8s conformance job with latest image and saw before failure:
```
+ kubetest2 tf --powervs-dns k8s-tests --powervs-image-name centos-stream-8 --powervs-region syd --powervs-zone syd05 --powervs-service-id c3f5354a-517e-4927-8523-890c4bf3d6c5 --powervs-ssh-key powercloud-bot-key --ssh-private-key /etc/secret-volume/ssh-privatekey --build-version v1.26.0-alpha.1.90+91a9ce28ac2486 --cluster-name config1-1663927026 --workers-count 2 --up --auto-approve --retry-on-tf-failure 3 --break-kubetest-on-upfail true --powervs-memory 32 --test=ginkgo -- --parallel 10 --flake-attempts 2 --test-package-bucket k8s-release-dev --test-package-dir ci --test-package-version v1.26.0-alpha.1.90+91a9ce28ac2486 '--focus-regex=\[Conformance\]' '--skip-regex=\[Serial\]'
/bin/bash: line 22: kubetest2: command not found
{"component":"entrypoint","error":"wrapped process failed: exit status 127","file":"k8s.io/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-09-23T09:57:08Z"}
```
+ kubetest2 tf --powervs-dns k8s-tests --powervs-image-name centos-stream-8 --powervs-region syd --powervs-zone syd05 --powervs-service-id c3f5354a-517e-4927-8523-890c4bf3d6c5 --powervs-ssh-key powercloud-bot-key --ssh-private-key /etc/secret-volume/ssh-privatekey --build-version v1.26.0-alpha.1.90+91a9ce28ac2486 --cluster-name config1-1663927026 --workers-count 2 --up --auto-approve --retry-on-tf-failure 3 --break-kubetest-on-upfail true --powervs-memory 32 --test=ginkgo -- --parallel 10 --flake-attempts 2 --test-package-bucket k8s-release-dev --test-package-dir ci --test-package-version v1.26.0-alpha.1.90+91a9ce28ac2486 '--focus-regex=\[Conformance\]' '--skip-regex=\[Serial\]'
/bin/bash: line 22: kubetest2: command not found
{"component":"entrypoint","error":"wrapped process failed: exit status 127","file":"k8s.io/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-09-23T09:57:08Z"}

**Comment by mkumatag** [comment]
> I did a test run of k8s conformance job with latest image and saw before failure:
> 
> ```
> + kubetest2 tf --powervs-dns k8s-tests --powervs-image-name centos-stream-8 --powervs-region syd --powervs-zone syd05 --powervs-service-id c3f5354a-517e-4927-8523-890c4bf3d6c5 --powervs-ssh-key powercloud-bot-key --ssh-private-key /etc/secret-volume/ssh-privatekey --build-version v1.26.0-alpha.1.90+91a9ce28ac2486 --cluster-name config1-1663927026 --workers-count 2 --up --auto-approve --retry-on-tf-failure 3 --break-kubetest-on-upfail true --powervs-memory 32 --test=ginkgo -- --parallel 10 --flake-attempts 2 --test-package-bucket k8s-release-dev --test-package-dir ci --test-package-version v1.26.0-alpha.1.90+91a9ce28ac2486 '--focus-regex=\[Conformance\]' '--skip-regex=\[Serial\]'
> /bin/bash: line 22: kubetest2: command not found
> {"component":"entrypoint","error":"wrapped process failed: exit status 127","file":"k8s.io/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-09-23T09:57:08Z"}
> ```
> 
> https://prow.ppc64le-cloud.org/view/gs/ppc64le-kubernetes/logs/test-periodic-kubernetes-containerd-conformance-test-ppc64le/1573249574758256640

This is happening because `go get` deprecated and will not install the binary in the latest golang we have updated in that image(1.18), for more information: https://go.dev/doc/go-get-install-deprecation, need to modify the jobs to use `go install` instead.

**Comment by mkumatag** [comment]
/hold
lemme submit the change for the same.

**Comment by mkumatag** [comment]
@Rajalakshmi-Girish here is the PR to fix this and need this before this merge https://github.com/ppc64le-cloud/test-infra/pull/338

**Comment by mkumatag** [comment]
@Rajalakshmi-Girish lets rerun the job and see how it goes?

**Pull request merged**
