### PR TITLE
Add tflint and fmt presubmit actions

### LINKED ISSUE #168: Add Terraform fmt and linter to powervs PR validation
We need to add following checks for OCP PowerVS automation PRs.
- [ ] `tflint` [1]
- [ ] `terraform fmt` [2]

[1] https://github.com/terraform-linters/tflint
[2] https://www.terraform.io/docs/cli/commands/fmt.html

### PR DESCRIPTION
**Pull request by yussufsh**
Fixes #168

Signed-off-by: Yussuf Shaikh <yussuf.shaikh@ibm.com>

### CODE REVIEW

**Comment by ltccci** [comment]
[Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.

**The list of commits with invalid commit messages**:

- [56dc605](https://github.com/ppc64le-cloud/test-infra/commits/56dc6056b6f23bf870040f6bccc06bd3174d9321) Add tflint and fmt presubmit actions

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/169#" title="Author self-approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[config/jobs/ocp-automation/OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/config/jobs/ocp-automation/OWNERS)~~ [yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by yussufsh** [comment]
/cc @mkumatag
Please take a good look at this first-hand. :-)

**Comment by yussufsh** [comment]
any updaate?

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> any update?

Sorry somehow missed this.
Will check now.

**Comment by Rajalakshmi-Girish** [comment]
The jobs are giving below error on using the usual `bot-ssh-secret` while running test-pj:
```
 Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
After I manually `docker pull` the images using private credentials, we get the below error for 
**pull-ocp4-upi-powervs-terraform-fmt:**
```
{"component":"unset","error":"wrapped process failed: exit status 3","file":"/go/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-04-13T07:00:44Z"}
```
[pull-ocp4-upi-powervs-terraform-fmt_log.txt](https://github.com/ppc64le-cloud/test-infra/files/6302128/pull-ocp4-upi-powervs-terraform-fmt_log.txt)

**pull-ocp4-upi-powervs-terraform-lint:**

Unable to created test-pod though the image wata727/tflint is available in cluster:
```
 Normal   BackOff    59s (x2 over 89s)  kubelet            Back-off pulling image "wata727/tflint"
  Warning  Failed     59s (x2 over 89s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    46s (x3 over 91s)  kubelet            Pulling image "wata727/tflint"
  Warning  Failed     45s (x3 over 90s)  kubelet            Error: ErrImagePull
  Warning  Failed     45s (x3 over 90s)  kubelet            Failed to pull image "wata727/tflint": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Comment by yussufsh** [comment]
**pull-ocp4-upi-powervs-terraform-fmt** is fine.. we need the pre-submit job to fail if no proper formatting is available.

No idea why it is trying to pull the image again in case of **pull-ocp4-upi-powervs-terraform-lint**

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> **pull-ocp4-upi-powervs-terraform-fmt** is fine.. we need the pre-submit job to fail if no proper formatting is available.
> 
> No idea why it is trying to pull the image again in case of **pull-ocp4-upi-powervs-terraform-lint**

I could run **pull-ocp4-upi-powervs-terraform-lint** on another cluster. Below is the log of test-pod that ran the job. @yussufsh does that mean the `tflint --module` command was successful?
```
Failed to load configurations. 3 error(s) occurred:

^[[31mError^[[0m: `install` module is not found. Did you run `terraform init`?

  on ocp.tf line 67, in module "install":
  67: ^[[1;4mmodule "install"^[[0m {

^[[31mError^[[0m: `nodes` module is not found. Did you run `terraform init`?

  on ocp.tf line 47, in module "nodes":
  47: ^[[1;4mmodule "nodes"^[[0m {

^[[31mError^[[0m: `prepare` module is not found. Did you run `terraform init`?

  on ocp.tf line 19, in module "prepare":
  19: ^[[1;4mmodule "prepare"^[[0m {

{"component":"unset","error":"wrapped process failed: exit status 2","file":"/go/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-04-13T14:50:21Z"}
```

**Comment by yussufsh** [comment]
> I could run **pull-ocp4-upi-powervs-terraform-lint** on another cluster. Below is the log of test-pod that ran the job. @yussufsh does that mean the `tflint --module` command was successful?
> 

yes

**Comment by yussufsh** [comment]
Can we merge now?

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> Can we merge now?
As I mentioned above, **failures indicated in the job** log are due to formating errors in the repo.
@mkumatag Please confirm if the errors in the repo be fixed before we have this job up and running?

**Comment by mkumatag** [comment]
> > 
> > 
> > Can we merge now?
> As I mentioned above, **failures indicated in the job** log are due to formating errors in the repo.
> @mkumatag Please confirm if the errors in the repo be fixed before we have this job up and running? 
> 
Let's fix all the errors and see green runs otherwise each PR will fail with those errors and won't allow to merge the PR..

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> > > Can we merge now?
> > > As I mentioned above, **failures indicated in the job** log are due to formating errors in the repo.
> > > @mkumatag Please confirm if the errors in the repo be fixed before we have this job up and running?
> 
> Let's fix all the errors and see green runs otherwise each PR will fail with those errors and won't allow to merge the PR..

@yussufsh Can you please fix the formatting errors in repo.
I shall re-run this job and confirm once you are done.

**Comment by yussufsh** [comment]
@mkumatag @Rajalakshmi-Girish I want to test this change with open PR https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/258

So I want to request you to merge the change and tests looks good and can be validated with the above PR.

**Comment by mkumatag** [comment]
> @mkumatag @Rajalakshmi-Girish I want to test this change with open PR [ocp-power-automation/ocp4-upi-powervs#258](https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/258)
> 
> So I want to request you to merge the change and tests looks good and can be validated with the above PR.

allright

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/169#pullrequestreview-638461151" title="LGTM">mkumatag</a>*, *<a href="https://github.com/ppc64le-cloud/test-infra/pull/169#" title="Author self-approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[config/jobs/ocp-automation/OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/config/jobs/ocp-automation/OWNERS)~~ [mkumatag,yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ltccci** [comment]
@yussufsh: Updated the `job-config` configmap in namespace `prow` at cluster `default` using the following files:
 - key `ocp4-upi-powervs-presubmit.yaml` using file `config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml`

<details>

In response to [this](https://github.com/ppc64le-cloud/test-infra/pull/169):

>Fixes #168
>
>Signed-off-by: Yussuf Shaikh <yussuf.shaikh@ibm.com>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by yussufsh** [comment]
So, the `tflint` failed because it needs `terraform init` before running the command.

**Pull request merged**
