### PR TITLE
Add issue_comment event to cherrypick plugin

### PR DESCRIPTION
**Pull request by Rajalakshmi-Girish**
The event `issue_comment` is to be added to cherrypick external pick for it to send the `issue_comment` to cherry picker endpoint. Please see the below log messages from hook component:
The `event-type` for yesterday's comment https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-803780447 is `issue_comment`.
```
{"author":"yussufsh","component":"hook","event-GUID":"56d1b000-8ad2-11eb-8028-b4ed95f9232f","event-type":"issue_comment","file":"prow/hook/events.go:330","func":"k8s.io/test-infra/prow/hook.(*Server).handleIssueCommentEvent","level":"info","msg":"Issue comment created.","org":"ocp-power-automation","pr":188,"repo":"ocp4-upi-powervm","severity":"info","time":"2021-03-22T05:49:17Z","url":"https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-803780447"}
{"author":"yussufsh","component":"hook","event-GUID":"56d1b000-8ad2-11eb-8028-b4ed95f9232f","event-type":"issue_comment","file":"prow/plugins/approve/approve.go:166","func":"k8s.io/test-infra/prow/plugins/approve.handleGenericComment","level":"debug","msg":"Event is not a creation of a comment on an open PR, skipping.","org":"ocp-power-automation","plugin":"approve","pr":188,"repo":"ocp4-upi-powervm","severity":"debug","time":"2021-03-22T05:49:17Z","url":"https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-803780447"}
{"author":"yussufsh","component":"hook","duration":"91.302µs","event-GUID":"56d1b000-8ad2-11eb-8028-b4ed95f9232f","event-type":"issue_comment","file":"prow/plugins/approve/approve.go:163","func":"k8s.io/test-infra/prow/plugins/approve.handleGenericComment.func1","level":"debug","msg":"Completed handleGenericComment","org":"ocp-power-automation","plugin":"approve","pr":188,"repo":"ocp4-upi-powervm","severity":"debug","time":"2021-03-22T05:49:17Z","url":"https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-803780447"}
```
```
{"author":"mkumatag","component":"hook","event-GUID":"85a169a0-8ad4-11eb-91b7-3d5f9044150e","event-type":"issue_comment","file":"prow/hook/events.go:330","func":"k8s.io/test-infra/prow/hook.(*Server).handleIssueCommentEvent","level":"info","msg":"Issue comment created.","org":"ocp-power-automation","pr":188,"repo":"ocp4-upi-powervm","severity":"info","time":"2021-03-22T06:04:54Z","url":"https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-803787565"}
{"author":"mkumatag","component":"hook","event-GUID":"85a169a0-8ad4-11eb-91b7-3d5f9044150e","event-type":"issue_comment","file":"prow/plugins/approve/approve.go:166","func":"k8s.io/test-infra/prow/plugins/approve.handleGenericComment","level":"debug","msg":"Event is not a creation of a comment on an open PR, skipping.","org":"ocp-power-automation","plugin":"approve","pr":188,"repo":"ocp4-upi-powervm","severity":"debug","time":"2021-03-22T06:04:54Z","url":"https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-803787565"}
{"author":"mkumatag","component":"hook","duration":"88.212µs","event-GUID":"85a169a0-8ad4-11eb-91b7-3d5f9044150e","event-type":"issue_comment","file":"prow/plugins/approve/approve.go:163","func":"k8s.io/test-infra/prow/plugins/approve.handleGenericComment.func1","level":"debug","msg":"Completed handleGenericComment","org":"ocp-power-automation","plugin":"approve","pr":188,"repo":"ocp4-upi-powervm","severity":"debug","time":"2021-03-22T06:04:54Z","url":"https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-803787565"}

```

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/159#" title="Author self-approved">Rajalakshmi-Girish</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mkumatag** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @mkumatag` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by yussufsh — APPROVED** [review]
/lgtm

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/159#" title="Author self-approved">Rajalakshmi-Girish</a>*, *<a href="https://github.com/ppc64le-cloud/test-infra/pull/159#pullrequestreview-618252080" title="LGTM">yussufsh</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mkumatag** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @mkumatag` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by mkumatag — APPROVED** [review]
/lgtm
/approve

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/159#pullrequestreview-618259470" title="Approved">mkumatag</a>*, *<a href="https://github.com/ppc64le-cloud/test-infra/pull/159#" title="Author self-approved">Rajalakshmi-Girish</a>*, *<a href="https://github.com/ppc64le-cloud/test-infra/pull/159#pullrequestreview-618252080" title="LGTM">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/OWNERS)~~ [mkumatag]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ltccci** [comment]
@Rajalakshmi-Girish: Updated the `plugins` configmap in namespace `prow` at cluster `default` using the following files:
 - key `plugins.yaml` using file `config/prow/plugins.yaml`

<details>

In response to [this](https://github.com/ppc64le-cloud/test-infra/pull/159):

>The event `issue_comment` is to be added to cherrypick external pick for it to send the `issue_comment` to cherry picker endpoint. Please see the below log messages from hook component:
>The `event-type` for yesterday's comment https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-803780447 is `issue_comment`.
>```
>{"author":"yussufsh","component":"hook","event-GUID":"56d1b000-8ad2-11eb-8028-b4ed95f9232f","event-type":"issue_comment","file":"prow/hook/events.go:330","func":"k8s.io/test-infra/prow/hook.(*Server).handleIssueCommentEvent","level":"info","msg":"Issue comment created.","org":"ocp-power-automation","pr":188,"repo":"ocp4-upi-powervm","severity":"info","time":"2021-03-22T05:49:17Z","url":"https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-803780447"}
>{"author":"yussufsh","component":"hook","event-GUID":"56d1b000-8ad2-11eb-8028-b4ed95f9232f","event-type":"issue_comment","file":"prow/plugins/approve/approve.go:166","func":"k8s.io/test-infra/prow/plugins/approve.handleGenericComment","level":"debug","msg":"Event is not a creation of a comment on an open PR, skipping.","org":"ocp-power-automation","plugin":"approve","pr":188,"repo":"ocp4-upi-powervm","severity":"debug","time":"2021-03-22T05:49:17Z","url":"https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-803780447"}
>{"author":"yussufsh","component":"hook","duration":"91.302µs","event-GUID":"56d1b000-8ad2-11eb-8028-b4ed95f9232f","event-type":"issue_comment","file":"prow/plugins/approve/approve.go:163","func":"k8s.io/test-infra/prow/plugins/approve.handleGenericComment.func1","level":"debug","msg":"Completed handleGenericComment","org":"ocp-power-automation","plugin":"approve","pr":188,"repo":"ocp4-upi-powervm","severity":"debug","time":"2021-03-22T05:49:17Z","url":"https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-803780447"}
>```
>```
>{"author":"mkumatag","component":"hook","event-GUID":"85a169a0-8ad4-11eb-91b7-3d5f9044150e","event-type":"issue_comment","file":"prow/hook/events.go:330","func":"k8s.io/test-infra/prow/hook.(*Server).handleIssueCommentEvent","level":"info","msg":"Issue comment created.","org":"ocp-power-automation","pr":188,"repo":"ocp4-upi-powervm","severity":"info","time":"2021-03-22T06:04:54Z","url":"https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-803787565"}
>{"author":"mkumatag","component":"hook","event-GUID":"85a169a0-8ad4-11eb-91b7-3d5f9044150e","event-type":"issue_comment","file":"prow/plugins/approve/approve.go:166","func":"k8s.io/test-infra/prow/plugins/approve.handleGenericComment","level":"debug","msg":"Event is not a creation of a comment on an open PR, skipping.","org":"ocp-power-automation","plugin":"approve","pr":188,"repo":"ocp4-upi-powervm","severity":"debug","time":"2021-03-22T06:04:54Z","url":"https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-803787565"}
>{"author":"mkumatag","component":"hook","duration":"88.212µs","event-GUID":"85a169a0-8ad4-11eb-91b7-3d5f9044150e","event-type":"issue_comment","file":"prow/plugins/approve/approve.go:163","func":"k8s.io/test-infra/prow/plugins/approve.handleGenericComment.func1","level":"debug","msg":"Completed handleGenericComment","org":"ocp-power-automation","plugin":"approve","pr":188,"repo":"ocp4-upi-powervm","severity":"debug","time":"2021-03-22T06:04:54Z","url":"https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188#issuecomment-803787565"}
>
>```


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
