### PR TITLE
Change checkconfig command in pull-test-infra-prow-checkconfig job

### PR DESCRIPTION
**Pull request by Rajalakshmi-Girish**
The presubmit job for https://github.com/ppc64le-cloud/test-infra/pull/444 still fails with below error:
```
could not start the process: fork/exec /checkconfig: no such file or directory
```
This change is required after the image tag upgrade.

Have verified this manually by creating a container and also had a look at the upstream job https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml#L75

```
[root@maxwells1 ~]# kubectl describe pod checkconfig2 | grep image
  Normal  Pulling    8m23s  kubelet            Pulling image "gcr.io/k8s-prow/checkconfig:v20240205-8f023a0da6"
  Normal  Pulled     8m22s  kubelet            Successfully pulled image "gcr.io/k8s-prow/checkconfig:v20240205-8f023a0da6" in 1.834609537s (1.834623899s including waiting)
[root@maxwells1 ~]# kubectl exec -it checkconfig2 -- /bin/sh
/ # /checkconfig version
/bin/sh: /checkconfig: not found
/ # checkconfig version
{"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:240","func":"main.main","level":"fatal","msg":"Error parsing options - invalid options: --config-path is mandatory","severity":"fatal","time":"2024-02-08T07:57:09Z"}
/ #
```

### CODE REVIEW

**Comment by Rajalakshmi-Girish** [comment]
> @Rajalakshmi-Girish: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> pull-test-infra-prow-checkconfig 	[c0f46a2](https://github.com/ppc64le-cloud/test-infra/commit/c0f46a236406544465af6e6f66b7eb9741b65d12) 	[link](https://prow.ppc64le-cloud.cis.ibm.net/view/s3/ppc64le-prow-logs/pr-logs/pull/ppc64le-cloud_test-infra/446/pull-test-infra-prow-checkconfig/1755504686401589248) 	true 	`/test pull-test-infra-prow-checkconfig`
> 
> [Full PR test history](https://prow.ppc64le-cloud.cis.ibm.net/pr-history?org=ppc64le-cloud&repo=test-infra&pr=446). [Your PR dashboard](https://prow.ppc64le-cloud.cis.ibm.net/pr?query=is:pr+state:open+author:Rajalakshmi-Girish).

@mkumatag This change should have been part of image tag upgrade by https://github.com/ppc64le-cloud/test-infra/pull/446
Hmm does this mean, I should update the job in prow infra from backend!

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by Rajalakshmi-Girish** [comment]
> /test pull-test-infra-prow-checkconfig

It is picking up the job that is currently existing.
Maybe I should update job-config from the back end?

**Comment by mkumatag** [comment]
@Rajalakshmi-Girish lets make this change in the backend and rerun the job

**Pull request merged**
