### PR TITLE
Use TF13 and no need for setting up plugins

### LINKED ISSUE #75: Update PowerVS job configs for all branches
- Use latest TF v0.13 for all branches.
- No need of manual plugins installation

### PR DESCRIPTION
**Pull request by yussufsh**
Fixes #75 

Signed-off-by: Yussuf Shaikh <yussuf.shaikh@ibm.com>

### CODE REVIEW

**Comment by ltccci** [comment]
[Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) mentions are not allowed in commit messages.

**The list of commits with invalid commit messages**:

- [a2aa754](https://github.com/ppc64le-cloud/test-infra/commits/a2aa754db32e709e41f91734c9baf715296bafb8) Use TF13 and no need for setting up plugins

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/76#" title="Author self-approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[config/jobs/ocp-automation/OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/config/jobs/ocp-automation/OWNERS)~~ [yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by mkumatag** [comment]
@yussufsh can you please the `fixes#` from the commit message

**Comment by ltccci** [comment]
@yussufsh: Updated the `job-config` configmap in namespace `prow` at cluster `default` using the following files:
 - key `ocp4-upi-powervs-presubmit.yaml` using file `config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-presubmit.yaml`

<details>

In response to [this](https://github.com/ppc64le-cloud/test-infra/pull/76):

>Fixes #75 
>
>Signed-off-by: Yussuf Shaikh <yussuf.shaikh@ibm.com>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by mkumatag** [comment]
> @yussufsh can you please the `fixes#` from the commit message

somehow @ltccci was happy even with `fixes#` tag.

**Pull request merged**
