### PR TITLE
Fix for current exception in cerberus deployment

### PR DESCRIPTION
**Pull request by Rajalakshmi-Girish**
The issue in upstream https://github.com/cloud-bulldozer/cerberus/issues/122 is causing exception in cerberus deployment.
This PR is to fix this failure by disabling the watch of schedulable masters through making it optional.
This PR is also increasing the **sleep interval between iterations to 1800s from the existing 60s value.**

**Changes to cerberus/start_cerberus.py:**
```
>         watch_schedulable_masters = config["cerberus"].get("watch_schedulable_masters", True)
140c141,143
<         master_nodes = kubecli.list_nodes("node-role.kubernetes.io/master")
---
>         master_nodes = []
>         if watch_schedulable_masters:
>                 master_nodes = kubecli.list_nodes("node-role.kubernetes.io/master")
212a216
>                                                       watch_schedulable_masters,
root@sajauddin-dev:~/rajalakshmi/fork/test-infra/config/prow/cluster#
```

**Changes in cerberus/cerberus/kubernetes/client.py:**
```
< def process_master_taint(master_nodes, iteration, iter_track_time):
---
> def process_master_taint(watch_schedulable_masters, master_nodes, iteration, iter_track_time):
319,322c319,323
<     if iteration % 10 == 1:
<         check_taint_start_time = time.time()
<         schedulable_masters = check_master_taint(master_nodes)
<         iter_track_time['check_master_taint'] = time.time() - check_taint_start_time
---
>     if watch_schedulable_masters:
>         if iteration % 10 == 1:
>             check_taint_start_time = time.time()
>             schedulable_masters = check_master_taint(master_nodes)
>             iter_track_time['check_master_taint'] = time.time() - check_taint_start_time

```

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/157#" title="Author self-approved">Rajalakshmi-Girish</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mkumatag** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @mkumatag` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by mkumatag — APPROVED** [review]
/lgtm
/approve

Let's apply the changes..

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/157#pullrequestreview-614921069" title="Approved">mkumatag</a>*, *<a href="https://github.com/ppc64le-cloud/test-infra/pull/157#" title="Author self-approved">Rajalakshmi-Girish</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/OWNERS)~~ [mkumatag]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> /lgtm
> /approve
> 
> Let's apply the changes..

The Cerberus Deployment got applied successfully. There are no exceptions or failures found in log:
```
2021-03-18 05:29:38,863 [INFO] Starting ceberus
2021-03-18 05:29:38,873 [INFO] Initializing client to talk to the Kubernetes cluster
2021-03-18 05:29:38,928 [INFO] Fetching cluster info
2021-03-18 05:29:39,305 [INFO] Kubernetes control plane is running at https://172.21.0.1:443

2021-03-18 05:29:39,305 [INFO] Publishing cerberus status at http://0.0.0.0:8080
2021-03-18 05:29:39,306 [INFO] Starting http server at http://0.0.0.0:8080

2021-03-18 05:29:39,318 [INFO] Slack integration has been enabled
               _
  ___ ___ _ __| |__   ___ _ __ _   _ ___
 / __/ _ \ '__| '_ \ / _ \ '__| | | / __|
| (_|  __/ |  | |_) |  __/ |  | |_| \__ \
 \___\___|_|  |_.__/ \___|_|   \__,_|___/


2021-03-18 05:29:39,347 [INFO] Daemon mode enabled, cerberus will monitor forever
2021-03-18 05:29:39,347 [INFO] Ignoring the iterations set

2021-03-18 05:29:40,084 [INFO] Iteration 1: Node status: True
2021-03-18 05:29:40,092 [INFO] HTTP requests served: 0

2021-03-18 05:29:40,093 [INFO] Check health of prow controller

**2021-03-18 05:29:40,616 [INFO] Prow controller Pod has No Error**
2021-03-18 05:29:40,617 [INFO] Skipping the prometheus query as the prometheus client couldn't be initilized

2021-03-18 05:29:40,617 [INFO] Skipping the prometheus query as the prometheus client couldn't be initilized

2021-03-18 05:29:40,617 [INFO] None

2021-03-18 05:29:40,617 [INFO] Sleeping for the specified duration: 1800
```
**Must wait to see how the notification appears when there is failure in prow-controller.**

**Pull request merged**
