### PR TITLE
Add ocp-power-automation/ocp4-playbooks-extras

### PR DESCRIPTION
**Pull request by yussufsh**
Signed-off-by: Yussuf Shaikh <yussuf.shaikh1@ibm.com>

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by yussufsh** [comment]
How much time does it take to apply this changes?
I am trying to use it @ https://github.com/ocp-power-automation/ocp4-playbooks-extras/pull/3
Also I do not see the labels synced.

**Comment by mkumatag** [comment]
> How much time does it take to apply these changes?
> I am trying to use it @ https://github.com/ocp-power-automation/ocp4-playbooks-extras/pull/3
> Also I do not see the labels synced.

It is cronjob based job.. not sure when it will run next.. 

cc @Rajalakshmi-Girish

**Comment by Rajalakshmi-Girish** [comment]
> Also I do not see the labels synced.

The cron job was not running on the prow setup.
Hmm, I happen to remove this while I was working on some improvisation with labels sync.
I have deployed it now. It runs at the 17th minute every hour. Should be synced in a while.

**Pull request merged**
