### PR TITLE
Set boskos host

### PR DESCRIPTION
**Pull request by Amulyam24**

### CODE REVIEW

**Comment by Amulyam24** [comment]
@mkumatag, I haven't received a mail about the org invitation yet. Could you please recheck?

**Comment by Amulyam24** [comment]
never mind, I did receive it, somehow missed it. Would you mind sending it again?

**Review by mkumatag — APPROVED** [review]
/lgtm
/approve
/ok-to-test
/hold for others to review @Rajalakshmi-Girish

**Comment by Amulyam24** [comment]
@Rajalakshmi-Girish, Please hold this for sometime. Have made a couple of changes to the deployments. Will validate it and let you know here once done.

**Comment by Amulyam24** [comment]
@Rajalakshmi-Girish, PTAL. We can proceed with this now. Have raised another PR for Boskos specs.

**Comment by Rajalakshmi-Girish** [comment]
@Amulyam24 Will this job create a network by name `capi-e2e-test` every time it runs OR only the ports are created to the already existing network?
I see the script trying to create network for every run, But there is no cleanup of network https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/scripts/ci-e2e.sh#L73
Is the network cleanup handled boskos? I ask this to include network resource into Survey of PowerVS/IBM Cloud :)

**Comment by Amulyam24** [comment]
> @Amulyam24 Will this job create a network by name `capi-e2e-test` every time it runs OR only the ports are created to the already existing network? I see the script trying to create network for every run, But there is no cleanup of network https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/scripts/ci-e2e.sh#L73 Is the network cleanup handled boskos? I ask this to include network resource into Survey of PowerVS/IBM Cloud :)

Ideally the resource name would be acquired via Boskos and yes, the cleanup is handled by boskos itself.

**Pull request merged**
