### PR TITLE
Add external plugin cherrypick

### PR DESCRIPTION
**Pull request by yussufsh**
Signed-off-by: Yussuf Shaikh <yussuf.shaikh@ibm.com>

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/144#" title="Author self-approved">yussufsh</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mkumatag** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @mkumatag` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by yussufsh** [comment]
/cc @mkumatag 
I am not sure if this is all what is needed to enable external plugin. But this looks to me a good start to enable cherrypick plugin on the repos.

**Comment by mkumatag** [comment]
> /cc @mkumatag
> I am not sure if this is all what is needed to enable external plugin. But this looks to me a good start to enable cherrypick plugin on the repos.

we are on the right path but not enough for making it work, was going through this link [here](https://github.com/kubernetes/test-infra/blob/2abb7ff26579325f6a335990003f665755c96d7a/prow/plugins/README.md#external-plugins) and need an endpoint that serves the requests(pull_request in this case)

I will hold at the moment till I deploy an endpoint

/hold

**Review by mkumatag — APPROVED** [review]
Actual cherrypick service is up and running now, we can safely merge this PR now..

/lgtm
/unhold

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/144#pullrequestreview-617015416" title="LGTM">mkumatag</a>*, *<a href="https://github.com/ppc64le-cloud/test-infra/pull/144#" title="Author self-approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/OWNERS)~~ [mkumatag]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ltccci** [comment]
@yussufsh: Updated the `plugins` configmap in namespace `prow` at cluster `default` using the following files:
 - key `plugins.yaml` using file `config/prow/plugins.yaml`

<details>

In response to [this](https://github.com/ppc64le-cloud/test-infra/pull/144):

>Signed-off-by: Yussuf Shaikh <yussuf.shaikh@ibm.com>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
