### PR TITLE
Fix the grafana ingress resource

### PR DESCRIPTION
**Pull request by mkumatag**
/cc @sudeeshjohn @Rajalakshmi-Girish

### CODE REVIEW

**Comment by sudeeshjohn** [comment]
@mkumatag this patch is there in https://github.com/ppc64le-cloud/test-infra/pull/181

**Comment by mkumatag** [comment]
> @mkumatag this patch is there in https://github.com/ppc64le-cloud/test-infra/pull/181

Anything pending in #181 other than reviewing the code?

**Comment by sudeeshjohn** [comment]
> Anything pending in #181 other than reviewing the code?

No.

**Pull request closed without merging**
