### PR TITLE
Adding postsubmit job for ocp4-upi-powervm

### PR DESCRIPTION
**Pull request by sudeeshjohn**
Post submit job  for ocp4-upi-powervm for updating github page repository , https://github.com/ocp-power-automation/ocp-power-automation.github.io

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/161#" title="Author self-approved">sudeeshjohn</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **yussufsh** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @yussufsh` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

<details open>
Needs approval from an approver in each of these files:

- **[config/jobs/ocp-automation/OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/config/jobs/ocp-automation/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ltccci** [comment]
@sudeeshjohn: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pull-test-infra-yamllint | 92b86adad24ca805b45293cf837230e803070bdc | [link](https://prow.ppc64le-cloud.org/view/s3/prow-logs/pr-logs/pull/ppc64le-cloud_test-infra/161/pull-test-infra-yamllint/1375428128104517632) | `/test pull-test-infra-yamllint`

[Full PR test history](https://prow.ppc64le-cloud.org/pr-history?org=ppc64le-cloud&repo=test-infra&pr=161). [Your PR dashboard](https://prow.ppc64le-cloud.org/pr?query=is:pr+state:open+author:sudeeshjohn).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by mkumatag** [comment]
@sudeeshjohn fix the error:

```
config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-postsubmit.yaml
2
  38:37     error    no new line character at the end of file  (new-line-at-end-of-file)
```

**Review by mkumatag — APPROVED** [review]
/lgtm
/hold for @Rajalakshmi-Girish review

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/161#pullrequestreview-622148784" title="LGTM">mkumatag</a>*, *<a href="https://github.com/ppc64le-cloud/test-infra/pull/161#" title="Author self-approved">sudeeshjohn</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[config/jobs/ocp-automation/OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/config/jobs/ocp-automation/OWNERS)~~ [mkumatag]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by Rajalakshmi-Girish** [comment]
@mkumatag Can we have a similar post submit job for `k8s-ansible` repo so that submodule for `kubetest2-plugins` can be updated automatically.

**Comment by ltccci** [comment]
@sudeeshjohn: Updated the `job-config` configmap in namespace `prow` at cluster `default` using the following files:
 - key `ocp4-upi-powervm-postsubmit.yaml` using file `config/jobs/ocp-automation/ocp4-upi-powervm/ocp4-upi-powervm-postsubmit.yaml`

<details>

In response to [this](https://github.com/ppc64le-cloud/test-infra/pull/161):

>Post submit job  for ocp4-upi-powervm for updating github page repository , https://github.com/ocp-power-automation/ocp-power-automation.github.io


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by mkumatag** [comment]
> @mkumatag Can we have a similar post submit job for `k8s-ansible` repo so that submodule for `kubetest2-plugins` can be updated automatically.

This is just a doc stuff, not much logic involved.. but the other one may need changes in the go code as well.. but something we can think about it for long term..

**Pull request merged**
