### PR TITLE
Changes to upgrade prow infra to v20211229-d20cd1c87e

### PR DESCRIPTION
**Pull request by Rajalakshmi-Girish**
Changes in this PR to include the upstream changes from below PRs:

- Slack reporter: https://github.com/kubernetes/test-infra/pull/24280
- Graffana deployment: https://github.com/kubernetes/test-infra/pull/24665
- Prow jobs defined in .yml files are also respected: https://github.com/kubernetes/test-infra/pull/24675

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
/lgtm
/approve

**Comment by Rajalakshmi-Girish** [comment]
> /lgtm /approve

Shall unhold this after applying the specs and if no error/failures.

**Comment by Rajalakshmi-Girish** [comment]
The Prow components are running fine and I don't see any significant errors in the logs.
Also, a new job https://prow.ppc64le-cloud.org/view/s3/prow-logs/logs/periodic-golang-master-build-ppc64le/1478950996808830976 ran after the updation of specs.
/unhold

**Pull request merged**
