### PR TITLE
Adding postsubmit job for ocp4-upi-powervs, ocp-powervm-faq, etc

### PR DESCRIPTION
**Pull request by sudeeshjohn**
Post submit job for updating documentation for ocp4-upi-powervs, ocp-powervm-faq, openshift-install-power and ocp4-upi-kvm in github pages at git@github.com:ocp-power-automation/ocp-power-automation.github.io.git

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/162#" title="Author self-approved">sudeeshjohn</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **yussufsh** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @yussufsh` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

<details open>
Needs approval from an approver in each of these files:

- **[config/jobs/ocp-automation/OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/config/jobs/ocp-automation/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/162#pullrequestreview-622653008" title="LGTM">mkumatag</a>*, *<a href="https://github.com/ppc64le-cloud/test-infra/pull/162#" title="Author self-approved">sudeeshjohn</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[config/jobs/ocp-automation/OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/config/jobs/ocp-automation/OWNERS)~~ [mkumatag]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by Rajalakshmi-Girish** [comment]
@sudeeshjohn @mkumatag Can we not club all these postsubmit jobs into one file and iterate the values? (Just to have less lines of code)
I am not sure if yaml supports this feature... I could not find any syntax straight away for having them in one file

**Review by Rajalakshmi-Girish — APPROVED** [review]
/lgtm

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/162#pullrequestreview-622653008" title="LGTM">mkumatag</a>*, *<a href="https://github.com/ppc64le-cloud/test-infra/pull/162#pullrequestreview-623095467" title="LGTM">Rajalakshmi-Girish</a>*, *<a href="https://github.com/ppc64le-cloud/test-infra/pull/162#" title="Author self-approved">sudeeshjohn</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[config/jobs/ocp-automation/OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/config/jobs/ocp-automation/OWNERS)~~ [mkumatag]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by mkumatag** [comment]
> @sudeeshjohn @mkumatag Can we not club all these postsubmit jobs into one file and iterate the values? (Just to have less lines of code)
> I am not sure if yaml supports this feature... I could not find any syntax straight away for having them in one file

not sure if we can do that but something we can explore in the future.
/unhold

**Comment by ltccci** [comment]
@sudeeshjohn: Updated the `job-config` configmap in namespace `prow` at cluster `default` using the following files:
 - key `ocp-powervm-faq-postsubmit.yaml` using file `config/jobs/ocp-automation/ocp-powervm-faq/ocp-powervm-faq-postsubmit.yaml`
 - key `ocp4-upi-kvm-postsubmit.yaml` using file `config/jobs/ocp-automation/ocp4-upi-kvm/ocp4-upi-kvm-postsubmit.yaml`
 - key `ocp4-upi-powervs-postsubmit.yaml` using file `config/jobs/ocp-automation/ocp4-upi-powervs/ocp4-upi-powervs-postsubmit.yaml`
 - key `openshift-install-power-postsubmit.yaml` using file `config/jobs/ocp-automation/openshift-install-power/openshift-install-power-postsubmit.yaml`

<details>

In response to [this](https://github.com/ppc64le-cloud/test-infra/pull/162):

>Post submit job for updating documentation for ocp4-upi-powervs, ocp-powervm-faq, openshift-install-power and ocp4-upi-kvm in github pages at git@github.com:ocp-power-automation/ocp-power-automation.github.io.git


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
