### PR TITLE
Changes to Prow specs for upgrading to v20210623-0c619adcf3

### PR DESCRIPTION
**Pull request by Rajalakshmi-Girish**
For the upgrade from `v20210305-64a6d4d83a` to `v20210623-0c619adcf3`, Below are the commits that got merged and seems relevant to us:
1.	https://github.com/kubernetes/test-infra/commit/e3209c7a0408b30c5422f4657a5aa14abf406b19 - **switch to rbac/v1**
2.	https://github.com/kubernetes/test-infra/commit/aa0d5ff86ecc0958039177960fd6d598c45be149 - **Switch all kubeconfig consumer deployments to use KUBECONFIG envvar**
3.	https://github.com/kubernetes/test-infra/commit/a17d860e81c816155810d67fb91507f804b0cce5 - **Horologium: Use a cached prowjob client**
4.	https://github.com/kubernetes/test-infra/commit/6f8a5585af00586c8eaee245ba0739d97fcd791b - **drop handling of gcs/ job url prefix**
5.	https://github.com/kubernetes/test-infra/commit/6274f8b8ea4c013e303f7f64934d18f041080795 - **Add missing dry-run=false to sinker args**
6.	https://github.com/kubernetes/test-infra/commit/354125e18e450d66ddbcafc8ff790c4531ea222d - **Updating the prowjob CRD to v1**
7.  https://github.com/kubernetes/test-infra/commit/2dd140be6d1da596efa647c3ce523a6446b03881 - **Add links lens to render new master-and-node-logs.txt file**
8. https://github.com/kubernetes/test-infra/commit/3f924cf00028706fc6aaad2986e301747a86b8c1 **Migrate plugins config to new format**

### CODE REVIEW

**Comment by mkumatag** [comment]
> @Rajalakshmi-Girish: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-test-infra-prow-checkconfig	[e9c5eec](https://github.com/ppc64le-cloud/test-infra/commit/e9c5eec4f179ebdcefb2694977e406ba2d4a1a6b)	[link](https://prow.ppc64le-cloud.org/view/s3/prow-logs/pr-logs/pull/ppc64le-cloud_test-infra/204/pull-test-infra-prow-checkconfig/1408400611791081472)	`/test pull-test-infra-prow-checkconfig`
> [Full PR test history](https://prow.ppc64le-cloud.org/pr-history?org=ppc64le-cloud&repo=test-infra&pr=204). [Your PR dashboard](https://prow.ppc64le-cloud.org/pr?query=is:pr+state:open+author:Rajalakshmi-Girish).

@Rajalakshmi-Girish not sure why it is failing here ^^^^

otherwise lgtm

**Comment by mkumatag** [comment]
> @Rajalakshmi-Girish: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-test-infra-prow-checkconfig	[e9c5eec](https://github.com/ppc64le-cloud/test-infra/commit/e9c5eec4f179ebdcefb2694977e406ba2d4a1a6b)	[link](https://prow.ppc64le-cloud.org/view/s3/prow-logs/pr-logs/pull/ppc64le-cloud_test-infra/204/pull-test-infra-prow-checkconfig/1408400611791081472)	`/test pull-test-infra-prow-checkconfig`
> [Full PR test history](https://prow.ppc64le-cloud.org/pr-history?org=ppc64le-cloud&repo=test-infra&pr=204). [Your PR dashboard](https://prow.ppc64le-cloud.org/pr?query=is:pr+state:open+author:Rajalakshmi-Girish).

probably this is because of this old entry here - https://github.com/ppc64le-cloud/test-infra/blob/master/config/jobs/ppc64le-cloud/test-infra/test-infra-presubmits.yaml#L24, can you please send a PR to update the image here first?

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> > @Rajalakshmi-Girish: The following test **failed**, say `/retest` to rerun all failed tests:
> > Test name	Commit	Details	Rerun command
> > pull-test-infra-prow-checkconfig	[e9c5eec](https://github.com/ppc64le-cloud/test-infra/commit/e9c5eec4f179ebdcefb2694977e406ba2d4a1a6b)	[link](https://prow.ppc64le-cloud.org/view/s3/prow-logs/pr-logs/pull/ppc64le-cloud_test-infra/204/pull-test-infra-prow-checkconfig/1408400611791081472)	`/test pull-test-infra-prow-checkconfig`
> > [Full PR test history](https://prow.ppc64le-cloud.org/pr-history?org=ppc64le-cloud&repo=test-infra&pr=204). [Your PR dashboard](https://prow.ppc64le-cloud.org/pr?query=is:pr+state:open+author:Rajalakshmi-Girish).
> 
> probably this is because of this old entry here - https://github.com/ppc64le-cloud/test-infra/blob/master/config/jobs/ppc64le-cloud/test-infra/test-infra-presubmits.yaml#L24, can you please send a PR to update the image here first?

Thanks for helping out!
Was finding it difficult to understand why it is failing.
Here is the PR. ptal, https://github.com/ppc64le-cloud/test-infra/pull/205

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by mkumatag** [comment]
@Rajalakshmi-Girish please redeploy the changes in the production IKS cluster

**Pull request merged**
