### PR TITLE
Add gcs configuration to kubernetes unit and conformance ppc64le periodic jobs

### PR DESCRIPTION
**Pull request by Rajalakshmi-Girish**
Ref: https://github.ibm.com/powercloud/container-dev/issues/1333

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/84#" title="Author self-approved">Rajalakshmi-Girish</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mkumatag** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @mkumatag` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by mkumatag** [comment]
Please fix the author's name and email, it is showing root right now.

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> Please fix the author's name and email, it is showing root right now.

I am not sure where you wanted me to change these details. @mkumatag Can you please elaborate.

**Comment by mkumatag** [comment]
> I am not sure where you wanted me to change these details. @mkumatag Can you please elaborate.

If you look at the author of this PR's commit it shows as `root` which is not correct, please amend the commit with the proper email and name and rebase the PR as well to accommodate the latest changes in the code.

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> > I am not sure where you wanted me to change these details. @mkumatag Can you please elaborate.
> 
> If you look at the author of this PR's commit it shows as `root` which is not correct, please amend the commit with the proper email and name and rebase the PR as well to accommodate the latest changes in the code.

Done. @mkumatag please check.

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/84#issuecomment-720344267" title="Approved">mkumatag</a>*, *<a href="https://github.com/ppc64le-cloud/test-infra/pull/84#" title="Author self-approved">Rajalakshmi-Girish</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/OWNERS)~~ [mkumatag]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ltccci** [comment]
@Rajalakshmi-Girish: Updated the `job-config` configmap in namespace `prow` at cluster `default` using the following files:
 - key `test-kubernetes-periodics.yaml` using file `config/jobs/periodic/kubernetes/test-kubernetes-periodics.yaml`

<details>

In response to [this](https://github.com/ppc64le-cloud/test-infra/pull/84):

>Ref: https://github.ibm.com/powercloud/container-dev/issues/1333
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
