### PR TITLE
update terraform version to latest for validate

### LINKED ISSUE #328: Update terraform version for ocp4-upi-powervm presubmit job
With new changes for https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/253 where Terraform version is updated we need to upgrade the terraform version used to validate the code to latest.

### PR DESCRIPTION
**Pull request by yussufsh**
Fixes #328

Signed-off-by: Yussuf Shaikh <yussuf.shaikh1@ibm.com>

### CODE REVIEW

**Comment by Rajalakshmi-Girish** [comment]
> [APPROVALNOTIFIER] This PR is **APPROVED**
> 
> This pull-request has been approved by: _[yussufsh](https://github.com/ppc64le-cloud/test-infra/pull/329#)_
> 
> The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).
> 
> The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)
> Needs approval from an approver in each of these files:

How come this PR got an automatic `approved` label?

**Comment by yussufsh** [comment]
> How come this PR got an automatic `approved` label?

https://github.com/ppc64le-cloud/test-infra/blob/master/config/jobs/ocp-automation/OWNERS

**Comment by yussufsh** [comment]
Do I really need to remove the `Fixes` message?

**Comment by Rajalakshmi-Girish** [comment]
> Do I really need to remove the `Fixes` message?

If I remember right, I usually include the Fixes message part of the PR comment message.

**Pull request merged**
