### PR TITLE
Auto assign the PRs for review

### PR DESCRIPTION
**Pull request by mkumatag**
This PR is for assigning the reviewers automatically from the list.

/cc @Rajalakshmi-Girish 
/assign

### CODE REVIEW

**Review by Rajalakshmi-Girish — APPROVED** [review]
/lgtm

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> /cat

@mkumatag why is this plugin not displaying cat pictures?
Any clue, please.

**Comment by mkumatag** [comment]
> > 
> > 
> > /cat
> 
> @mkumatag why is this plugin not displaying cat pictures?
> Any clue, please.

It is suppose to be

/meow

But I don't it will work, because prow is not working because of DNS issues in the IKS cluster..

**Pull request merged**
