### PR TITLE
Upgrade prow cluster specs to latest community version

### PR DESCRIPTION
**Pull request by Rajalakshmi-Girish**
Upgrade prow cluster specs to latest community version `v20210305-64a6d4d83a`.

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/150#" title="Author self-approved">Rajalakshmi-Girish</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mkumatag** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @mkumatag` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by mkumatag** [comment]
/lgtm

can we apply the changes and see how it goes? will merge if no issues.

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> /lgtm
> 
> can we apply the changes and see how it goes? will merge if no issues.

I always get error of below kind when I apply the specs on IKS Prow cluster:
```
Name: "crier", Namespace: "prow"
from server for: "crier_rbac.yaml": roles.rbac.authorization.k8s.io "crier" is forbidden: User "IAM#rajalakshmi.girish1@ibm.com" cannot get resource "roles" in API group "rbac.authorization.k8s.io" in the namespace "prow"
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1, Resource=roles", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=Role"
Name: "crier", Namespace: "test-pods"
from server for: "crier_rbac.yaml": roles.rbac.authorization.k8s.io "crier" is forbidden: User "IAM#rajalakshmi.girish1@ibm.com" cannot get resource "roles" in API group "rbac.authorization.k8s.io" in the namespace "test-pods"
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1beta1, Resource=rolebindings", GroupVersionKind: "rbac.authorization.k8s.io/v1beta1, Kind=RoleBinding"
Name: "crier", Namespace: "prow"
from server for: "crier_rbac.yaml": rolebindings.rbac.authorization.k8s.io "crier" is forbidden: User "IAM#rajalakshmi.girish1@ibm.com" cannot get resource "rolebindings" in API group "rbac.authorization.k8s.io" in the namespace "prow"
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1beta1, Resource=rolebindings", GroupVersionKind: "rbac.authorization.k8s.io/v1beta1, Kind=RoleBinding"
Name: "crier", Namespace: "test-pods"
from server for: "crier_rbac.yaml": rolebindings.rbac.authorization.k8s.io "crier" is forbidden: User "IAM#rajalakshmi.girish1@ibm.com" cannot get resource "rolebindings" in API group "rbac.authorization.k8s.io" in the namespace "test-pods"
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1beta1, Resource=roles", GroupVersionKind: "rbac.authorization.k8s.io/v1beta1, Kind=Role"
Name: "deck", Namespace: "prow"
```

**Comment by Rajalakshmi-Girish** [comment]
As roles and bindings did not have any changes, those forbidden errors do not seem to matter!

The deployments got applied successfully and I don't see any errors in the logs.
As the pod-utility images are not yet updated in config.yaml, the old images will be used by CI Jobs.

@mkumatag Please let me know if anything else should be verified before we push these changes.

**Comment by mkumatag** [comment]
> @mkumatag Please let me know if anything else should be verified before we push these changes.

thats all I need, lemme merge

**Review by mkumatag — APPROVED** [review]

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/test-infra/pull/150#pullrequestreview-608559981" title="Approved">mkumatag</a>*, *<a href="https://github.com/ppc64le-cloud/test-infra/pull/150#" title="Author self-approved">Rajalakshmi-Girish</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Ftest-infra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ppc64le-cloud/test-infra/blob/master/OWNERS)~~ [mkumatag]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ltccci** [comment]
@Rajalakshmi-Girish: Updated the `config` configmap in namespace `prow` at cluster `default` using the following files:
 - key `config.yaml` using file `config/prow/config.yaml`

<details>

In response to [this](https://github.com/ppc64le-cloud/test-infra/pull/150):

>Upgrade prow cluster specs to latest community version `v20210305-64a6d4d83a`.


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
