### PR TITLE
Fix release-0.5 and release-0.6 vpc periodic jobs template names

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
- Fix release-0.5 and release-0.6 vpc periodic jobs template names

### CODE REVIEW

**Review by Amulyam24 — APPROVED** [review]
/lgtm

**Comment by Prajyot-Parab** [comment]
@Rajalakshmi-Girish Please merge this one.

**Review by Rajalakshmi-Girish — APPROVED** [review]
/lgtm

**Comment by mkumatag** [comment]
@Rajalakshmi-Girish please avoid merging anything manually :)

**Comment by Rajalakshmi-Girish** [comment]
> @Rajalakshmi-Girish please avoid merging anything manually :)

I thought so :|
But again, was thinking maybe they this urgently.
Shall not do now on 👍

**Pull request merged**
