### PR TITLE
Update vpc e2e flavor

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>

### CODE REVIEW

**Comment by mkumatag** [comment]
waiting on https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/1043 to merge

**Comment by Amulyam24** [comment]
Boskos cleanup for VPC doesn't yet handle cleanup for load balancers. Would be good to have that before we merge this PR. I can raise a PR by EOD if that's okay.

**Comment by Prajyot-Parab** [comment]
@mkumatag @Amulyam24 this one can be merged now

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
