### PR TITLE
Change centos image name to skip the GET image error

### PR DESCRIPTION
**Pull request by Rajalakshmi-Girish**
To avoid below error with prow jobs:
```
failed to perform Get Image Operation for image centos-8-stream-20gb with error [GET /pcloud/v1/cloud-instances/{cloud_instance_id}/images/{image_id}][500] pcloudCloudinstancesImagesGetInternalServerError  &{Code:0 Description:an error has occurred; please try again: unable to get image 37091d0f-a4f6-42d8-8cb5-8d71b34307c6: Unable to get Image 37091d0f-a4f6-42d8-8cb5-8d71b34307c6: Resource not found: [GET https://192.168.24.137:9292/v2/images/37091d0f-a4f6-42d8-8cb5-8d71b34307c6], error message: {"message": "No image found with ID 37091d0f-a4f6-42d8-8cb5-8d71b34307c6<br /><br />\n\n\n", "code": "404 Not Found", "title": "Not Found"} Error:internal server error Message:}[0m
```

### CODE REVIEW

**Comment by mkumatag** [comment]
@Rajalakshmi-Girish hope this is a temp fix

**Comment by Rajalakshmi-Girish** [comment]
@mkumatag we can leave the image name as it is in the future too.
After raising of support ticket and follow-up, we can delete the image with the old image name `centos-8-stream-20gb`

**Review by mkumatag — APPROVED** [review]
/lgtm
/approve

**Comment by Rajalakshmi-Girish** [comment]
As jobs are passing with the old image name itself, this change is not needed!

**Pull request closed without merging**
